import { Category, Product, PromoCode } from './types';

export const categories: Category[] = [
  { id: 1, name: "Fresh Vegetables", slug: "vegetables", emoji: "🥦", description: "Farm fresh greens & organics" },
  { id: 2, name: "Fresh Fruits", slug: "fruits", emoji: "🍎", description: "Seasonal & exotic handpicked fruits" },
  { id: 3, name: "Dairy & Breakfast", slug: "dairy", emoji: "🥛", description: "Milk, eggs, yogurt, butter & bread" },
  { id: 4, name: "Munchies & Snacks", slug: "munchies", emoji: "🍟", description: "Chips, nuts, puffs & savory bites" },
  { id: 5, name: "Cold Drinks & Juices", slug: "drinks", emoji: "🥤", description: "Sodas, fresh juices & energy drinks" },
  { id: 6, name: "Chocolates & Sweets", slug: "sweets", emoji: "🍫", description: "Artisan chocolates, candies & desserts" },
  { id: 7, name: "Instant & Frozen", slug: "instant", emoji: "🍜", description: "Noodles, pasta, pizzas & frozen snacks" },
  { id: 8, name: "Bakery & Biscuits", slug: "bakery", emoji: "🥐", description: "Artisanal breads, cookies & cakes" },
  { id: 9, name: "Pantry Essentials", slug: "pantry", emoji: "🍚", description: "Rice, grains, oils & gourmet spices" }
];

export const products: Product[] = [
  // Vegetables
  {
    id: 101,
    name: "Farm Fresh Red Onion",
    price: 35,
    originalPrice: 45,
    category: "vegetables",
    image: "🧅",
    unit: "1 kg",
    time: "8 MINS",
    rating: 4.8,
    reviewsCount: 342,
    description: "Crisp, pungent locally sourced red onions packed with rich flavor, perfect for salads, curries, and roasts.",
    badge: "Bestseller",
    inStock: true,
    shelfLife: "2 weeks",
    origin: "Nashik Farms",
    nutrition: { calories: "40 kcal/100g", protein: "1.1g", carbs: "9.3g", fat: "0.1g" }
  },
  {
    id: 102,
    name: "Organic Vine Tomatoes",
    price: 38,
    originalPrice: 48,
    category: "vegetables",
    image: "🍅",
    unit: "500 g",
    time: "9 MINS",
    rating: 4.9,
    reviewsCount: 512,
    description: "Plump, juicy vine-ripened tomatoes grown organically without synthetic pesticides.",
    badge: "Organic",
    inStock: true,
    shelfLife: "7 days",
    origin: "Sunlit Organic Orchards",
    nutrition: { calories: "18 kcal/100g", protein: "0.9g", carbs: "3.9g", fat: "0.2g" }
  },
  {
    id: 103,
    name: "Crunchy Baby Carrots",
    price: 32,
    originalPrice: 42,
    category: "vegetables",
    image: "🥕",
    unit: "500 g",
    time: "8 MINS",
    rating: 4.7,
    reviewsCount: 198,
    description: "Sweet, crunchy baby carrots washed and peeled for quick snacking, stir-fries, or dips.",
    inStock: true,
    shelfLife: "10 days",
    origin: "Ooty Organics",
    nutrition: { calories: "41 kcal/100g", protein: "0.9g", carbs: "9.6g", fat: "0.2g" }
  },
  {
    id: 104,
    name: "Crisp Green Broccoli",
    price: 65,
    originalPrice: 85,
    category: "vegetables",
    image: "🥦",
    unit: "1 head (400g)",
    time: "10 MINS",
    rating: 4.9,
    reviewsCount: 275,
    description: "Dense florets of fresh, tender green broccoli rich in vitamins C and K.",
    badge: "Superfood",
    inStock: true,
    shelfLife: "5 days",
    origin: "Valley Greens",
    nutrition: { calories: "34 kcal/100g", protein: "2.8g", carbs: "6.6g", fat: "0.4g" }
  },
  {
    id: 105,
    name: "Fresh Baby Spinach",
    price: 25,
    originalPrice: 35,
    category: "vegetables",
    image: "🥬",
    unit: "250 g",
    time: "7 MINS",
    rating: 4.8,
    reviewsCount: 420,
    description: "Tender hydroponic baby spinach leaves, pre-washed and ready to toss into green smoothies or salads.",
    inStock: true,
    shelfLife: "4 days",
    origin: "HydroFarm Fresh",
    nutrition: { calories: "23 kcal/100g", protein: "2.9g", carbs: "3.6g", fat: "0.4g" }
  },
  {
    id: 106,
    name: "Hass Avocados",
    price: 149,
    originalPrice: 199,
    category: "vegetables",
    image: "🥑",
    unit: "2 pcs (Ripe)",
    time: "9 MINS",
    rating: 4.9,
    reviewsCount: 680,
    description: "Creamy, buttery ready-to-eat Hass avocados packed with healthy monounsaturated fats.",
    badge: "Ripe & Ready",
    inStock: true,
    shelfLife: "4 days",
    origin: "Sunny Grove",
    nutrition: { calories: "160 kcal/100g", protein: "2g", carbs: "8.5g", fat: "14.7g" }
  },

  // Fruits
  {
    id: 201,
    name: "Golden Robusta Bananas",
    price: 45,
    originalPrice: 55,
    category: "fruits",
    image: "🍌",
    unit: "6 pcs",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 920,
    description: "Naturally ripened sweet bananas packed with potassium and natural energy.",
    badge: "Top Pick",
    inStock: true,
    shelfLife: "5 days",
    origin: "Robusta Orchards",
    nutrition: { calories: "89 kcal/100g", protein: "1.1g", carbs: "22.8g", fat: "0.3g" }
  },
  {
    id: 202,
    name: "Crisp Royal Gala Apples",
    price: 129,
    originalPrice: 160,
    category: "fruits",
    image: "🍎",
    unit: "4 pcs (~600g)",
    time: "10 MINS",
    rating: 4.8,
    reviewsCount: 460,
    description: "Sweet, crunchy Royal Gala apples with thin red skin and juicy white flesh.",
    inStock: true,
    shelfLife: "14 days",
    origin: "Himachal Orchards",
    nutrition: { calories: "52 kcal/100g", protein: "0.3g", carbs: "13.8g", fat: "0.2g" }
  },
  {
    id: 203,
    name: "Sweet Seedless Watermelon",
    price: 99,
    originalPrice: 130,
    category: "fruits",
    image: "🍉",
    unit: "1 whole (approx 2.5kg)",
    time: "12 MINS",
    rating: 4.7,
    reviewsCount: 310,
    description: "Deep red, ultra-refreshing seedless watermelon cut fresh daily.",
    inStock: true,
    shelfLife: "6 days",
    origin: "Farm Fresh Melons",
    nutrition: { calories: "30 kcal/100g", protein: "0.6g", carbs: "7.6g", fat: "0.2g" }
  },
  {
    id: 204,
    name: "Organic Blueberries",
    price: 149,
    originalPrice: 189,
    category: "fruits",
    image: "🫐",
    unit: "125 g clamshell",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 540,
    description: "Sweet, antioxidant-rich blueberries hand-harvested and chilled instantly.",
    badge: "Antioxidant Rich",
    inStock: true,
    shelfLife: "7 days",
    origin: "BerryFields Organics",
    nutrition: { calories: "57 kcal/100g", protein: "0.7g", carbs: "14.5g", fat: "0.3g" }
  },
  {
    id: 205,
    name: "Fresh Juicy Strawberries",
    price: 119,
    originalPrice: 150,
    category: "fruits",
    image: "🍓",
    unit: "250 g box",
    time: "8 MINS",
    rating: 4.8,
    reviewsCount: 380,
    description: "Bright red, fragrant strawberries with natural sweetness and high vitamin C.",
    inStock: true,
    shelfLife: "4 days",
    origin: "Mahabaleshwar Farms",
    nutrition: { calories: "32 kcal/100g", protein: "0.7g", carbs: "7.7g", fat: "0.3g" }
  },

  // Dairy & Breakfast
  {
    id: 301,
    name: "Organic Whole Milk",
    price: 58,
    originalPrice: 66,
    category: "dairy",
    image: "🥛",
    unit: "1 Liter Bottle",
    time: "7 MINS",
    rating: 4.9,
    reviewsCount: 1120,
    description: "Creamy, pasteurized farm fresh whole milk with natural calcium and vitamin D3.",
    badge: "Essential",
    inStock: true,
    shelfLife: "8 days",
    origin: "Meadow Fresh Dairy",
    nutrition: { calories: "62 kcal/100ml", protein: "3.2g", carbs: "4.8g", fat: "3.5g" }
  },
  {
    id: 302,
    name: "Free-Range Large Brown Eggs",
    price: 95,
    originalPrice: 120,
    category: "dairy",
    image: "🥚",
    unit: "12 pcs carton",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 880,
    description: "Ethically farmed brown eggs with vibrant golden yolks, rich in high-quality protein.",
    badge: "Free Range",
    inStock: true,
    shelfLife: "21 days",
    origin: "Pasture Pride Poultry",
    nutrition: { calories: "72 kcal/egg", protein: "6.3g", carbs: "0.4g", fat: "4.8g" }
  },
  {
    id: 303,
    name: "Artisan Sourdough Loaf",
    price: 75,
    originalPrice: 95,
    category: "dairy",
    image: "🍞",
    unit: "500 g sliced",
    time: "9 MINS",
    rating: 4.8,
    reviewsCount: 290,
    description: "Slow-fermented artisan sourdough bread with a crispy crust and soft airy crumb.",
    inStock: true,
    shelfLife: "4 days",
    origin: "Crust & Crumb Bakery",
    nutrition: { calories: "230 kcal/100g", protein: "8g", carbs: "45g", fat: "1.2g" }
  },
  {
    id: 304,
    name: "Greek Style Vanilla Yogurt",
    price: 85,
    originalPrice: 110,
    category: "dairy",
    image: "🥣",
    unit: "450 g tub",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 410,
    description: "Thick, probiotic-rich Greek yogurt infused with real vanilla bean pods.",
    inStock: true,
    shelfLife: "14 days",
    origin: "Epigamia Pure",
    nutrition: { calories: "95 kcal/100g", protein: "9g", carbs: "7g", fat: "3.5g" }
  },
  {
    id: 305,
    name: "Pure Salted Butter",
    price: 115,
    originalPrice: 130,
    category: "dairy",
    image: "🧈",
    unit: "250 g block",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 530,
    description: "Golden butter churned from rich fresh cream with a delicate pinch of salt.",
    inStock: true,
    shelfLife: "30 days",
    origin: "Amul Pure Dairy",
    nutrition: { calories: "717 kcal/100g", protein: "0.8g", carbs: "0.7g", fat: "81g" }
  },

  // Munchies & Snacks
  {
    id: 401,
    name: "Sea Salt Kettle Cooked Chips",
    price: 40,
    originalPrice: 50,
    category: "munchies",
    image: "🥔",
    unit: "150 g pouch",
    time: "6 MINS",
    rating: 4.7,
    reviewsCount: 620,
    description: "Extra-crunchy thick-cut kettle potato chips seasoned with natural rock salt.",
    badge: "Trending",
    inStock: true,
    shelfLife: "4 months",
    origin: "Golden Crisp Snacks",
    nutrition: { calories: "510 kcal/100g", protein: "6g", carbs: "54g", fat: "29g" }
  },
  {
    id: 402,
    name: "Zesty Cheese & Jalapeño Nachos",
    price: 60,
    originalPrice: 75,
    category: "munchies",
    image: "🌮",
    unit: "175 g pack",
    time: "7 MINS",
    rating: 4.8,
    reviewsCount: 390,
    description: "Stone-ground corn tortilla chips dusted with aged cheese and fiery jalapeño seasoning.",
    inStock: true,
    shelfLife: "3 months",
    origin: "Cornitos Crisps",
    nutrition: { calories: "490 kcal/100g", protein: "7g", carbs: "60g", fat: "24g" }
  },
  {
    id: 403,
    name: "Roasted Truffle & Sea Salt Almonds",
    price: 179,
    originalPrice: 220,
    category: "munchies",
    image: "🥜",
    unit: "120 g zip pack",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 230,
    description: "Premium almonds slow-roasted in truffle aromatics and Himalayan pink salt.",
    badge: "Gourmet",
    inStock: true,
    shelfLife: "6 months",
    origin: "NutriNosh Gourmet",
    nutrition: { calories: "590 kcal/100g", protein: "21g", carbs: "19g", fat: "50g" }
  },
  {
    id: 404,
    name: "Buttery Movie Theater Popcorn",
    price: 45,
    originalPrice: 60,
    category: "munchies",
    image: "🍿",
    unit: "100 g bag",
    time: "6 MINS",
    rating: 4.6,
    reviewsCount: 310,
    description: "Fluffy popped corn tossed in rich melted butter and a delicate crunch of salt.",
    inStock: true,
    shelfLife: "2 months",
    origin: "PopNation",
    nutrition: { calories: "450 kcal/100g", protein: "8g", carbs: "55g", fat: "22g" }
  },

  // Cold Drinks & Juices
  {
    id: 501,
    name: "Zero Sugar Sparkling Cola",
    price: 40,
    originalPrice: 45,
    category: "drinks",
    image: "🥤",
    unit: "500 ml Chilled Can",
    time: "6 MINS",
    rating: 4.7,
    reviewsCount: 780,
    description: "Classic refreshing fizzy cola taste with zero calories and zero sugar, served ice cold.",
    badge: "Chilled",
    inStock: true,
    shelfLife: "6 months",
    origin: "Thums Up Zero",
    nutrition: { calories: "0 kcal", protein: "0g", carbs: "0g", fat: "0g" }
  },
  {
    id: 502,
    name: "100% Fresh Cold-Pressed Orange Juice",
    price: 119,
    originalPrice: 149,
    category: "drinks",
    image: "🍹",
    unit: "1 Liter Carafe",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 610,
    description: "Pure Nagpur oranges squeezed cold with juicy pulp, no added sugar or preservatives.",
    badge: "No Added Sugar",
    inStock: true,
    shelfLife: "5 days",
    origin: "Raw Pressery",
    nutrition: { calories: "45 kcal/100ml", protein: "0.7g", carbs: "10.4g", fat: "0.2g" }
  },
  {
    id: 503,
    name: "Tender Coconut Water",
    price: 49,
    originalPrice: 60,
    category: "drinks",
    image: "🥥",
    unit: "330 ml Tetrapak",
    time: "7 MINS",
    rating: 4.8,
    reviewsCount: 450,
    description: "100% pure raw tender coconut water loaded with natural electrolytes and minerals.",
    inStock: true,
    shelfLife: "3 months",
    origin: "Coastal Coconut Farms",
    nutrition: { calories: "19 kcal/100ml", protein: "0.7g", carbs: "3.7g", fat: "0.2g" }
  },
  {
    id: 504,
    name: "Organic Sparkling Kombucha (Ginger Lemon)",
    price: 99,
    originalPrice: 120,
    category: "drinks",
    image: "🧃",
    unit: "350 ml Glass Bottle",
    time: "8 MINS",
    rating: 4.8,
    reviewsCount: 190,
    description: "Fermented live sparkling tea with spicy ginger and zesty lemon.",
    inStock: true,
    shelfLife: "60 days",
    origin: "Mountain Kombucha",
    nutrition: { calories: "15 kcal/100ml", protein: "0.2g", carbs: "3.2g", fat: "0g" }
  },

  // Chocolates & Sweets
  {
    id: 601,
    name: "Belgian Dark Chocolate Sea Salt (70%)",
    price: 125,
    originalPrice: 160,
    category: "sweets",
    image: "🍫",
    unit: "100 g bar",
    time: "7 MINS",
    rating: 4.9,
    reviewsCount: 540,
    description: "Velvety single-origin dark chocolate sprinkled with fleur de sel crystals.",
    badge: "Premium",
    inStock: true,
    shelfLife: "12 months",
    origin: "Maison Chocolat",
    nutrition: { calories: "550 kcal/100g", protein: "7.8g", carbs: "35g", fat: "41g" }
  },
  {
    id: 602,
    name: "Gourmet Fruit & Sour Gummy Candies",
    price: 65,
    originalPrice: 85,
    category: "sweets",
    image: "🍬",
    unit: "150 g pouch",
    time: "6 MINS",
    rating: 4.7,
    reviewsCount: 310,
    description: "Soft chewy real fruit juice gummies with a mouth-puckering sour sugar coating.",
    inStock: true,
    shelfLife: "6 months",
    origin: "Sweetie Bites",
    nutrition: { calories: "340 kcal/100g", protein: "4g", carbs: "78g", fat: "0.5g" }
  },
  {
    id: 603,
    name: "Creamy Hazelnut Gelato Tub",
    price: 199,
    originalPrice: 249,
    category: "sweets",
    image: "🍨",
    unit: "500 ml Pint",
    time: "9 MINS",
    rating: 5.0,
    reviewsCount: 420,
    description: "Silky Italian gelato made with roasted hazelnuts and fresh cream, kept insulated frozen.",
    badge: "Chilled Safe",
    inStock: true,
    shelfLife: "6 months",
    origin: "Gelateria Bella",
    nutrition: { calories: "210 kcal/100g", protein: "4.5g", carbs: "22g", fat: "11g" }
  },

  // Instant & Frozen
  {
    id: 701,
    name: "Korean Spicy Kimchi Ramen",
    price: 75,
    originalPrice: 95,
    category: "instant",
    image: "🍜",
    unit: "120 g Bowl",
    time: "7 MINS",
    rating: 4.8,
    reviewsCount: 840,
    description: "Springy noodles in a rich savory-spicy broth packed with freeze-dried kimchi flakes and veggies.",
    badge: "Quick Cook",
    inStock: true,
    shelfLife: "9 months",
    origin: "Seoul Kitchen",
    nutrition: { calories: "480 kcal/pack", protein: "10g", carbs: "72g", fat: "16g" }
  },
  {
    id: 702,
    name: "Stonebaked Margherita Pizza",
    price: 189,
    originalPrice: 249,
    category: "instant",
    image: "🍕",
    unit: "350 g (Cook in 8 mins)",
    time: "10 MINS",
    rating: 4.9,
    reviewsCount: 380,
    description: "Woodfired sourdough crust topped with tomato sauce, fresh mozzarella & sweet basil.",
    inStock: true,
    shelfLife: "3 months",
    origin: "Nonna's Hearth",
    nutrition: { calories: "260 kcal/100g", protein: "11g", carbs: "32g", fat: "9.5g" }
  },

  // Bakery
  {
    id: 801,
    name: "All-Butter French Croissants",
    price: 99,
    originalPrice: 130,
    category: "bakery",
    image: "🥐",
    unit: "2 pcs Freshly Baked",
    time: "8 MINS",
    rating: 4.9,
    reviewsCount: 470,
    description: "Golden, flaky, layered croissants baked every morning using Grade A churned butter.",
    badge: "Fresh Baked",
    inStock: true,
    shelfLife: "2 days",
    origin: "The Bakehouse",
    nutrition: { calories: "390 kcal/100g", protein: "7.5g", carbs: "42g", fat: "21g" }
  },
  {
    id: 802,
    name: "Belgian Chocolate Chip Cookies",
    price: 89,
    originalPrice: 110,
    category: "bakery",
    image: "🍪",
    unit: "6 pcs pack",
    time: "7 MINS",
    rating: 4.8,
    reviewsCount: 360,
    description: "Soft-baked chewy cookies loaded with dark and milk Belgian chocolate chunks.",
    inStock: true,
    shelfLife: "10 days",
    origin: "Cookie Corner",
    nutrition: { calories: "460 kcal/100g", protein: "5.5g", carbs: "62g", fat: "22g" }
  },

  // Pantry
  {
    id: 901,
    name: "Royal Aged Basmati Rice",
    price: 145,
    originalPrice: 180,
    category: "pantry",
    image: "🍚",
    unit: "1 kg Bag",
    time: "10 MINS",
    rating: 4.9,
    reviewsCount: 510,
    description: "Extra long aromatic grains aged for 2 years for fluffy, non-sticky fragrant rice dishes.",
    inStock: true,
    shelfLife: "18 months",
    origin: "Himalayan Grains",
    nutrition: { calories: "350 kcal/100g", protein: "7.9g", carbs: "77g", fat: "0.5g" }
  },
  {
    id: 902,
    name: "Extra Virgin Cold-Pressed Olive Oil",
    price: 349,
    originalPrice: 420,
    category: "pantry",
    image: "🫒",
    unit: "500 ml Glass Bottle",
    time: "9 MINS",
    rating: 5.0,
    reviewsCount: 290,
    description: "First cold pressed from selected olives with a fruity, peppery finish.",
    badge: "100% EVOO",
    inStock: true,
    shelfLife: "18 months",
    origin: "Mediterranean Pure",
    nutrition: { calories: "824 kcal/100ml", protein: "0g", carbs: "0g", fat: "92g" }
  }
];

export const promoCodes: PromoCode[] = [
  {
    code: "QUICK20",
    discountType: "percentage",
    value: 20,
    minOrder: 199,
    description: "20% off on orders above ₹199 (Max ₹100)"
  },
  {
    code: "FRESH10",
    discountType: "fixed",
    value: 50,
    minOrder: 249,
    description: "₹50 flat discount on orders above ₹249"
  },
  {
    code: "SUPER50",
    discountType: "percentage",
    value: 50,
    minOrder: 399,
    description: "50% mega discount up to ₹150 on orders above ₹399"
  }
];
